### ISSUE TITLE
VSSSearchCardsHTTPRequest: response body: []

### ISSUE THREAD

**Issue by malaypatel11** [VirgilSecurity/VirgilKeysiOS#10]
Sometimes got data.

Used twilio plus virgil. 

    [[VirgilHelperClass sharedInstance].virgil.Cards searchCardsWithIdentities:@["key"] completion:^(NSArray<VSSVirgilCard *>* vsenderCard, NSError *error)
 
vsenderCard.count always 0.

What is the issue ?

**Comment by SanjoDeundiak** [comment]
@malaypatel11, sorry for late response.
Are you sure you have successfully registered any user cards using identity=@"key"? Maybe you can provide some snippets and/or logs in debug mode, so I can have more details.
Also, check "error" argument inside your callback, maybe it contains details

**Comment by SanjoDeundiak** [comment]
Closed due to inactivity
