### ISSUE TITLE
Carthage or Manual Installation support?

### ISSUE THREAD

**Issue by sirvon** [VirgilSecurity/VirgilKeysiOS#5]
How can I use this lib as a manually installed framework or with carthage?

thanks for the service

**Comment by SanjoDeundiak** [comment]
@sirvon at this moment CocoaPods is the only officially supported way of distribution.
However, you can build frameworks on your own. You will need two frameworks:
1. VirgilSDK https://github.com/VirgilSecurity/virgil-sdk-x
2. VirgilCrypto https://github.com/VirgilSecurity/virgil-foundation-x
I recommend pulling last available versions using git tags.

Inside repositories you will find XCode projects/workspaces with Framework targets which should be built without any problems. But, if you want to run your application on both device and simulator, likely you will need to build framework separately for simulator and iOS and then combine binaries into 'fat' framework, more about this topic can be found on the internet, for example here:
http://stackoverflow.com/questions/29634466/how-to-export-fat-cocoa-touch-framework-for-simulator-and-device

P.S. I recommend using CocoaPods, so you can get all security updates in time.

**Comment by SanjoDeundiak** [comment]
@sirvon as of version 4.2.0 Virgil SDK can be installed using Carthage
