### ISSUE TITLE
dyld: Library not loaded

### ISSUE THREAD

**Issue by AngeloMateus** [VirgilSecurity/VirgilKeysiOS#53]
Hey guys I'm getting this issue when building for IOS:

dyld: Library not loaded: @rpath/VirgilSDK.framework/VirgilSDK

I'm using Cocoapods Xcode 11.5 onto IOS 13.5.1
Any idea why this is happening?

Thanks

**Comment by krudos** [comment]
i am having the same issue

**Comment by v-ken** [comment]
Same issue when using React Native

**Comment by SashaMihalache** [comment]
Having the same issue when trying with React Native, any news about this?
