### ISSUE TITLE
Support for arm64 simulator architecture

### ISSUE THREAD

**Issue by jakov-clay** [VirgilSecurity/VirgilKeysiOS#54]
Will you support arm64 simulator architecture for M1 processor simulators?

I get this error when I try to build.
`building for iOS Simulator, but linking in dylib built for iOS, file '......./Pods/VSCCrypto/Carthage/iOS/VSCCommon.framework/VSCCommon' for architecture arm64`

**Comment by SergeySeroshtan** [comment]
Hi!
Thanks for paying attention to the Virgil SDKs.
We're currently working on this issue and will distribute fix ASAP.

**Comment by SergeySeroshtan** [comment]
@jakov-clay can you check [this workaround ](https://narlei.com/development/apple-m1-xcode-error-when-build-in-simulator/)?

**Comment by SergeySeroshtan** [comment]
Also the next answer can help
https://github.com/AppsFlyerSDK/AppsFlyerFramework/issues/150#issuecomment-764432643

**Comment by jakov-clay** [comment]
Hi @SergeySeroshtan,
yes, I'm using the workarounds at the moment.
You can also include those in podspec of your framework until you have a time to take care of this. It omits need for workaround from integrators side.
`s.pod_target_xcconfig = { 'EXCLUDED_ARCHS[sdk=iphonesimulator*]' => 'arm64' }
  s.user_target_xcconfig = { 'EXCLUDED_ARCHS[sdk=iphonesimulator*]' => 'arm64' }`

I'm asking because I have a framework which has your frameworks as dependency. I wanted to provide arm64 simulator support but can't do that until you do :)

I just wanted to make sure you are aware of this and have it somewhere in plan. Is there an ETA maybe?

Thanks for answers.

**Comment by SergeySeroshtan** [comment]
@jakov-clay,
thanks for suggestions.
At the very moment we check possibility to use `XCFramework` bundle format to figure out this issue.
What approach you are using for your framework?

**Comment by jakov-clay** [comment]
Yes, you are right, you need to support XCFramework format to be able add that missing arch.
I'm using XCFramework format.

**Comment by jakov-clay** [comment]
With version 8.0.0 this issue is resolved
