### ISSUE TITLE
Error when linking VirgilCryptoFoundation arm64 iOS Simulator with bitcode enabled

### ISSUE THREAD

**Issue by jakov-clay** [VirgilSecurity/VirgilKeysiOS#56]
Hi,
I'm really glad that you decided to move to xcframework and support arm64 iOS Simulator.

I have some issues when building some of your library dependencies for this architecture.

`ld: bitcode bundle could not be generated because '/xxxx/DerivedData/Build/Products/Release-iphonesimulator/XCFrameworkIntermediates/VSCCrypto/Common/VSCCommon.framework/VSCCommon' was built without full bitcode. All frameworks and dylibs for bitcode must be generated from Xcode Archive or Install build file 'xxxxx/DerivedData/Build/Products/Release-iphonesimulator/XCFrameworkIntermediates/VSCCrypto/Common/VSCCommon.framework/VSCCommon' for architecture arm64 `

I have a framework that I build with your library as dependency. I can't seem to find a way to prevent this problem. I have to build my framework with bitcode enabled.
Is it maybe possible that you did not build VSCCommon framework with xcodebuild archive command?
Here is a screenshot of Xcode error:
<img width="1437" alt="Screenshot 2022-02-03 at 17 33 33" src="https://user-images.githubusercontent.com/56873230/152386222-fdb90610-26fc-4d4c-998a-cfacfcee6e99.png">

**Comment by SergeySeroshtan** [comment]
Hi @jakov-clay.
Would you, please, create a test project that reproduce this issue?

**Comment by jakov-clay** [comment]
It was issue on my side.
