### ISSUE TITLE
XCode 9 

### ISSUE THREAD

**Issue by ghost** [VirgilSecurity/VirgilKeysiOS#8]
Hi ,

Do you have the updated library for XCode 9 and iOS 11 as target

**Comment by SanjoDeundiak** [comment]
@nanduahmed-sikka update will be available soon, though using Carthage it's OK to use current version with Xcode 9 and iOS 11.

**Comment by SanjoDeundiak** [comment]
@nanduahmed-sikka updated for Xcode 9 in version 4.7.0

**Comment by ghost** [comment]
Thanks @SanjoDeundiak  for your update
